import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localized = {
    'en': {
      'appName': 'GYMOX',
      'welcome': 'Welcome back',
      'welcomeBack': 'Welcome back to GYMOX',
      'login': 'Login',
      'register': 'Register',
      'logout': 'Logout',
      'email': 'Email',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'fullName': 'Full Name',
      'phone': 'Phone Number',
      'forgotPassword': 'Forgot Password?',
      'resetPassword': 'Reset Password',
      'sendResetLink': 'Send Reset Link',
      'resetDescription': 'Enter your email address and we\'ll send you a link to reset your password',
      'dontHaveAccount': "Don't have an account?",
      'haveAccount': 'Already have an account?',
      'createAccount': 'Create Account',
      'fillDetails': 'Fill in your details to get started',
      'fieldRequired': 'Required',
      'passwordMin': 'At least 6 characters',
      'passwordMismatch': 'Passwords do not match',
      'home': 'Home',
      'profile': 'Profile',
      'membership': 'Membership',
      'attendance': 'Attendance',
      'workout': 'Workout',
      'payments': 'Payments',
      'notifications': 'Notifications',
      'editProfile': 'Edit Profile',
      'changePhoto': 'Change Photo',
      'save': 'Save',
      'cancel': 'Cancel',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'noData': 'No data available',
      'noMembership': 'No active membership',
      'active': 'Active',
      'expired': 'Expired',
      'frozen': 'Frozen',
      'plan': 'Plan',
      'startDate': 'Start Date',
      'endDate': 'End Date',
      'remainingDays': 'Remaining Days',
      'status': 'Status',
      'totalVisits': 'Total Visits',
      'lastCheckIn': 'Last Check In',
      'checkIn': 'Check In',
      'checkInSuccess': 'Checked in successfully!',
      'alreadyCheckedIn': 'Already checked in today',
      'amount': 'Amount',
      'date': 'Date',
      'method': 'Method',
      'receipt': 'Receipt',
      'exercises': 'Exercises',
      'sets': 'Sets',
      'reps': 'Reps',
      'notes': 'Notes',
      'markAllRead': 'Mark All Read',
      'noNotifications': 'No notifications',
      'workoutName': 'Workout Name',
      'quickActions': 'Quick Actions',
      'confirmLogout': 'Are you sure you want to logout?',
      'sar': 'SAR',
    },
    'ar': {
      'appName': 'جيموكس',
      'welcome': 'مرحباً بعودتك',
      'welcomeBack': 'مرحباً بعودتك إلى جيموكس',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'logout': 'تسجيل الخروج',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirmPassword': 'تأكيد كلمة المرور',
      'fullName': 'الاسم الكامل',
      'phone': 'رقم الهاتف',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'resetPassword': 'إعادة تعيين كلمة المرور',
      'sendResetLink': 'إرسال رابط إعادة التعيين',
      'resetDescription': 'أدخل بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور',
      'dontHaveAccount': 'ليس لديك حساب؟',
      'haveAccount': 'لديك حساب بالفعل؟',
      'createAccount': 'إنشاء حساب',
      'fillDetails': 'أدخل بياناتك للبدء',
      'fieldRequired': 'مطلوب',
      'passwordMin': 'على الأقل 6 أحرف',
      'passwordMismatch': 'كلمة المرور غير متطابقة',
      'home': 'الرئيسية',
      'profile': 'الملف الشخصي',
      'membership': 'العضوية',
      'attendance': 'الحضور',
      'workout': 'التمارين',
      'payments': 'المدفوعات',
      'notifications': 'الإشعارات',
      'editProfile': 'تعديل الملف الشخصي',
      'changePhoto': 'تغيير الصورة',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'success': 'تم بنجاح',
      'noData': 'لا توجد بيانات',
      'noMembership': 'لا توجد عضوية نشطة',
      'active': 'نشط',
      'expired': 'منتهي',
      'frozen': 'معلق',
      'plan': 'الخطة',
      'startDate': 'تاريخ البداية',
      'endDate': 'تاريخ النهاية',
      'remainingDays': 'الأيام المتبقية',
      'status': 'الحالة',
      'totalVisits': 'إجمالي الزيارات',
      'lastCheckIn': 'آخر تسجيل حضور',
      'checkIn': 'تسجيل حضور',
      'checkInSuccess': 'تم تسجيل الحضور بنجاح!',
      'alreadyCheckedIn': 'تم تسجيل الحضور اليوم بالفعل',
      'amount': 'المبلغ',
      'date': 'التاريخ',
      'method': 'طريقة الدفع',
      'receipt': 'الإيصال',
      'exercises': 'التمارين',
      'sets': 'المجموعات',
      'reps': 'التكرارات',
      'notes': 'ملاحظات',
      'markAllRead': 'تحديد الكل كمقروء',
      'noNotifications': 'لا توجد إشعارات',
      'workoutName': 'اسم التمرين',
      'quickActions': 'إجراءات سريعة',
      'confirmLogout': 'هل أنت متأكد من تسجيل الخروج؟',
      'sar': 'ر.س',
    },
  };

  static String getString(String key, String locale) {
    return _localized[locale]?[key] ?? _localized['en']?[key] ?? key;
  }

  static String of(String key, BuildContext context) {
    final locale = Localizations.localeOf(context).languageCode;
    return getString(key, locale);
  }
}
